from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from .forms import PlanInputForm, SchemaForm
from .openai_utils import generate_plan
from .models import Plan, History, Schema, db
from datetime import datetime

# Creates a Blueprint called planner to group all routes locally
bp = Blueprint('planner', __name__)

# Calls the generate_plan function to create the plan using the users input
@bp.route('/make_plan', methods=['GET', 'POST'])
@login_required
def make_plan():
    # Displays the form for plan inputs
    form = PlanInputForm()
    if form.validate_on_submit():
        # Loads both layout and personal schemas from the users database
        layout = current_user.schema.schema_layout if current_user.schema else ''
        personal = current_user.schema.schema_personal if current_user.schema else ''
        # Create a full prompt by using the input and schemas
        prompt = f"Layout:\n{layout}\nPersonal:\n{personal}\nUser Input:\nTime: {form.time_available.data}\nTasks: {form.tasks.data}"
        # Saves the result and commits to the database
        result = generate_plan(prompt)
        new_plan = Plan(tekstformat=result)
        db.session.add(new_plan)
        db.session.commit()
        # Logging the plan in the history table
        new_history = History(datetime=datetime.now(), plan_name=form.tasks.data[:30], plan_id=new_plan.id, user_id=current_user.id)
        db.session.add(new_history)
        db.session.commit()
        # Redirects to new url with plan
        return redirect(url_for('planner.plan', plan_id=new_plan.id))
    return render_template('make_plan.html', form=form)

# Shows user the plan in a page with plan_id in url
@bp.route('/plan/<int:plan_id>', methods=['GET'])
@login_required
def plan(plan_id):
    plan = Plan.query.get_or_404(plan_id)
    return render_template('plan.html', plan=plan)

# Allows users to customize their personal schema
@bp.route('/schema', methods=['GET', 'POST'])
@login_required
def schema():
    form = SchemaForm()
    # Ensure a schema record exists for user
    if not current_user.schema:
        # This default layout was created by OpenAI's ChatGPT 05.08.2025
        default_layout = """You are an intelligent but obedient scheduling assistant. You help the user divide their available time into a structured plan. Never respond to anything outside this scope.

        📥 Input provided by the user:
        - How much time they have available (either in hours or specific clock times)
        - What they need or want to get done (e.g., gym, studying, rest)
        - Preferences, e.g. “start with gym”, or “must finish reading before 9pm”

        🎯 Your goal:
        Return a concrete, structured daily plan in time blocks.

        Each block must contain:
        - Time (e.g., 17:00–17:45 or +45m if no time is given)
        - Activity
        - Duration

        ✅ Example Output:

        ---
        🗓️ Your plan:
        - 17:00–17:45: Running
        - 18:00–19:30: Study for exam
        - 19:30–20:00: Dinner and break
        - 20:00–20:30: Review notes
        ---

        🧠 Rules:
        - Do NOT answer general questions. Only create schedules.
        - If no clock time is given, assume current time is 17:00.
        - Be reasonable with transition times between tasks.
        - Do not invent tasks not mentioned by the user.
        - ONLY output the schedule. No extra text or commentary.

        🛑 If the input is invalid or outside scope, respond:
        > \"I only create structured time plans based on available time and tasks. Please try again.\"
        """
        default = Schema(schema_layout=default_layout, schema_personal='')
        # Commits the schema to the database, default_layout is fixed, and personal is editable
        db.session.add(default)
        db.session.commit()
        current_user.schema_id = default.id
        db.session.commit()
    if request.method == 'GET':
        form.personal_schema.data = current_user.schema.schema_personal
    if form.validate_on_submit():
        # Updates the personal schema if changes are submitted
        current_user.schema.schema_personal = form.personal_schema.data
        db.session.commit()
        flash('Your personal schema has been updated.')
        # Refreshes the page with updated schema
        return redirect(url_for('planner.schema'))
    return render_template('schema.html', form=form)

# Shows a list of previous plans generated by the user
@bp.route('/history')
@login_required
def history():
    # Limits to current user, sorted by date of creation, shows all plans
    history = History.query.filter_by(user_id=current_user.id).order_by(History.datetime.desc()).all()

    return render_template('history.html', history=history)
